webtalk_init -webtalk_dir C:/Users/SAHAN/DarkShadow/campus/Sem2/Computer archi/Labs/Lab6/Lab5/Lab5.sim/sim_1/behav/xsim/xsim.dir/Counter_Sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  6 15:09:45 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e2595bc2-dacf-4946-87b4-e3ba18c6c5fb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8dab84c0305644719659b9216864cbe0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7188_KB" -context "xsim\\usage"
webtalk_transmit -clientid 363234310 -regid "" -xml C:/Users/SAHAN/DarkShadow/campus/Sem2/Computer archi/Labs/Lab6/Lab5/Lab5.sim/sim_1/behav/xsim/xsim.dir/Counter_Sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/SAHAN/DarkShadow/campus/Sem2/Computer archi/Labs/Lab6/Lab5/Lab5.sim/sim_1/behav/xsim/xsim.dir/Counter_Sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/SAHAN/DarkShadow/campus/Sem2/Computer archi/Labs/Lab6/Lab5/Lab5.sim/sim_1/behav/xsim/xsim.dir/Counter_Sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
